# Week 5 In-class Exercise on ANN with churn.csv

In [1]:
#Hide Warnings
import warnings
warnings.filterwarnings('ignore')

In [2]:
#Import Libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv('churn.csv')

In [4]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(7), object(2)
memory usage: 859.5+ KB


In [6]:
df.describe()

CreditScore           Age        Tenure        Balance  NumOfProducts  \
count  10000.000000  10000.000000  10000.000000   10000.000000   10000.000000   
mean     650.528800     38.921800      5.012800   76485.889288       1.530200   
std       96.653299     10.487806      2.892174   62397.405202       0.581654   
min      350.000000     18.000000      0.000000       0.000000       1.000000   
25%      584.000000     32.000000      3.000000       0.000000       1.000000   
50%      652.000000     37.000000      5.000000   97198.540000       1.000000   
75%      718.000000     44.000000      7.000000  127644.240000       2.000000   
max      850.000000     92.000000     10.000000  250898.090000       4.000000   

         HasCrCard  IsActiveMember  EstimatedSalary        Exited  
count  10000.00000    10000.000000     10000.000000  10000.000000  
mean       0.70550        0.515100    100090.239881      0.203700  
std        0.45584        0.499797     57510.492818      0.402769  
min        0.00000        0.000000        11.580000      0.000000  
25%        0.00000        0.000000     51002.110000      0.000000  
50%        1.00000        1.000000    100193.915000      0.000000  
75%        1.00000        1.000000    149388.247500      0.000000  
max        1.00000        1.000000    199992.480000      1.000000

# Split data into X and y and encode categorical data Geography & Gender

In [7]:
X = df.drop('Exited', axis = 1)
X.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [8]:
y = df.Exited
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [9]:
X=pd.get_dummies(X,columns=['Geography'],drop_first=True)

In [10]:
X=pd.get_dummies(X,columns=['Gender'],drop_first=True)

In [11]:
X.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Geography_Germany  Geography_Spain  \
0               1        101348.88                  0                0   
1               1        112542.58                  0                1   
2               0        113931.57                  0                0   
3               0         93826.63                  0                0   
4               1         79084.10                  0                1   

   Gender_Male  
0            0  
1            0  
2            0  
3            0  
4            0

In [12]:
X.shape

(10000, 11)

# Split data into test & train and scale

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [14]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Build the ANN Network with Sklearn MLPClassifier

In [15]:
from sklearn.neural_network import MLPClassifier
model = MLPClassifier(hidden_layer_sizes = (6,), activation = 'relu', solver = 'adam', batch_size = 10, max_iter = 100, random_state = 0)

In [16]:
#Train the Nework
model.fit(X_train, y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size=10, beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(6,), learning_rate='constant',
              learning_rate_init=0.001, max_iter=100, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=0, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [17]:
#Testing the Network
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
y_pred

array([False, False, False, ..., False, False, False])

# Compare the output to actual data

In [18]:
from sklearn.metrics import confusion_matrix, classification_report
confusionMatrix = confusion_matrix(y_test, y_pred)
print(confusionMatrix)


[[1522   73]
 [ 206  199]]


In [19]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.95      0.92      1595
           1       0.73      0.49      0.59       405

    accuracy                           0.86      2000
   macro avg       0.81      0.72      0.75      2000
weighted avg       0.85      0.86      0.85      2000



In [20]:
#Run another model with different hidden layer size
model_2 = MLPClassifier(hidden_layer_sizes = (8,), activation = 'relu', solver = 'adam', batch_size = 10, max_iter = 100, random_state = 0)

In [21]:
#Train the Nework
model_2.fit(X_train, y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size=10, beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(8,), learning_rate='constant',
              learning_rate_init=0.001, max_iter=100, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=0, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [22]:
#Testing the Network
y_pred = model_2.predict(X_test)
y_pred = (y_pred > 0.5)
y_pred

array([False, False, False, ..., False, False, False])

# Compare the output to actual data

In [23]:
confusionMatrix = confusion_matrix(y_test, y_pred)
print(confusionMatrix)


[[1513   82]
 [ 194  211]]


In [24]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.89      0.95      0.92      1595
           1       0.72      0.52      0.60       405

    accuracy                           0.86      2000
   macro avg       0.80      0.73      0.76      2000
weighted avg       0.85      0.86      0.85      2000



# Now try Keras ANN

In [25]:
#Import model
from keras import Sequential
model_k = Sequential()

Using TensorFlow backend.


In [27]:
#Create Layers
from keras.layers import Dense
input_layer = Dense(units = 6, activation = 'relu', kernel_initializer = 'uniform')
model_k.add(input_layer)
hidden_layer = Dense(units = 6, activation = 'relu', kernel_initializer = 'uniform' )
model_k.add(hidden_layer)
output_layer = Dense(units = 1, activation = 'sigmoid', kernel_initializer = 'uniform')
model_k.add(output_layer)

In [28]:
#Compile the model Optimizer, Loss Function, metrics
model_k.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Instructions for updating:
Colocations handled automatically by placer.


In [33]:
y_train = y_train.values

In [34]:
y_train

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [37]:
y_test = y_test.values

In [39]:
y_test

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [40]:
X_train.shape

(8000, 11)

In [41]:
#Fit the model, batch size, #nof epochs
model_k.fit(X_train, y_train, batch_size = 10, epochs = 100)

Instructions for updating:
Use tf.cast instead.
Epoch 1/100
8000/8000 [==============================] - 1s 151us/step - loss: 0.5005 - acc: 0.7951
Epoch 2/100
8000/8000 [==============================] - 1s 102us/step - loss: 0.4308 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.4262 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 102us/step - loss: 0.4221 - acc: 0.7979
Epoch 5/100
8000/8000 [==============================] - 1s 101us/step - loss: 0.4162 - acc: 0.8252
Epoch 6/100
8000/8000 [==============================] - 1s 99us/step - loss: 0.4065 - acc: 0.8277
Epoch 7/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.3973 - acc: 0.8285
Epoch 8/100
8000/8000 [==============================] - 1s 102us/step - loss: 0.3889 - acc: 0.8302
Epoch 9/100
8000/8000 [==============================] - 1s 98us/step - loss: 0.3820 - acc: 0.8386
Epoch 10/100
8000/8000 [==============================

8000/8000 [==============================] - 1s 103us/step - loss: 0.3452 - acc: 0.8601
Epoch 80/100
8000/8000 [==============================] - 1s 100us/step - loss: 0.3465 - acc: 0.8591
Epoch 81/100
8000/8000 [==============================] - 1s 102us/step - loss: 0.3463 - acc: 0.8600
Epoch 82/100
8000/8000 [==============================] - 1s 100us/step - loss: 0.3462 - acc: 0.8584
Epoch 83/100
8000/8000 [==============================] - 1s 123us/step - loss: 0.3458 - acc: 0.8577
Epoch 84/100
8000/8000 [==============================] - 1s 135us/step - loss: 0.3458 - acc: 0.8626
Epoch 85/100
8000/8000 [==============================] - 1s 129us/step - loss: 0.3453 - acc: 0.8595
Epoch 86/100
8000/8000 [==============================] - 1s 136us/step - loss: 0.3461 - acc: 0.8612
Epoch 87/100
8000/8000 [==============================] - 1s 131us/step - loss: 0.3455 - acc: 0.8590
Epoch 88/100
8000/8000 [==============================] - 1s 122us/step - loss: 0.3453 - acc: 0.8579
Epo

In [42]:
#Testing the Network
y_pred = model_k.predict(X_test)
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [43]:
from sklearn.metrics import confusion_matrix, classification_report
confusionMatrix = confusion_matrix(y_test, y_pred)
print(confusionMatrix)

[[1531   64]
 [ 211  194]]


In [44]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1595
           1       0.75      0.48      0.59       405

    accuracy                           0.86      2000
   macro avg       0.82      0.72      0.75      2000
weighted avg       0.85      0.86      0.85      2000

